In [1]:
import pandas as pd

To use Git LFS, you must install the Git LFS client.

See https://git-lfs.github.com for more information.

Run: `git lfs install`

In [7]:
philly_bus = pd.read_feather('FilteredData/business_philly.feather')
philly_reviews = pd.read_feather('FilteredData/review_philly.feather')
philly_users = pd.read_feather('FilteredData/user_philly.feather')

In [8]:
# Check the data
philly_bus.head()

,index,_id,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,31,631ea3b2a5cde8cc0d6eec47,-0M0b-XhtFagyLmsBtOe8w,Paris Wine Bar,2303 Fairmount Ave,Philadelphia,PA,19130,39.967439,-75.175452,3.5,18,0,"{'Alcohol': ""u'full_bar'"", 'OutdoorSeating': '...","Bars, Nightlife, Restaurants, French, Wine Bars","{'Thursday': '17:0-0:0', 'Friday': '17:0-0:0',..."
1,32,631ea3b0a5cde8cc0d6dfa60,-0PN_KFPtbnLQZEeb23XiA,Mr Wong's Chinese Restaurant,1849 Wolf St,Philadelphia,PA,19145,39.923048,-75.178078,3.5,9,0,"{'OutdoorSeating': 'False', 'BusinessAcceptsCr...","Restaurants, Chinese","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'..."
2,33,631ea3aea5cde8cc0d6d5a50,-0TffRSXXIlBYVbb5AwfTg,IndeBlue Modern Indian Food & Spirits,205 South 13th St,Philadelphia,PA,19107,39.948508,-75.161969,4.5,1097,1,"{'RestaurantsReservations': 'True', 'NoiseLeve...","Cocktail Bars, Food Delivery Services, Nightli...","{'Monday': '0:0-0:0', 'Tuesday': '16:0-22:0', ..."
3,37,631ea3b0a5cde8cc0d6e2ef1,-0eUa8TsXFFy0FCxHYmrjg,Waterfront Gourmet Cafe & Deli,3131 Walnut St,Philadelphia,PA,19104,39.952446,-75.187321,4.0,26,0,"{'BikeParking': 'True', 'RestaurantsGoodForGro...","Caterers, Sandwiches, Delis, Restaurants, Cafe...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,40,631ea3ada5cde8cc0d6d26c0,-0fvhILrC9UsQ6gLNpZlTQ,David's Southern Fried Pies,8601 Frankford Ave,Philadelphia,PA,19136,40.046191,-75.015090,4.5,18,0,"{'BusinessAcceptsBitcoin': 'False', 'Caters': ...","Desserts, Food","{'Monday': '0:0-0:0', 'Tuesday': '12:0-19:0', ..."

In [9]:
philly_reviews

,_id,review_id,user_id,business_id,stars,useful,funny,cool,text,date,compliment_count
0,631e9f7fedf65856ab0dfe3b,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1.0,1.0,2.0,1.0,I am a long term frequent customer of this est...,2015-09-23 23:10:31,NaN
1,631e9f7fedf65856ab0dfe3e,8JFGBuHMoiNDyfcxuWNtrA,smOvOajNG0lS4Pq7d8g4JQ,RZtGWDLCAtuipwaZ-UfjmQ,4.0,0.0,0.0,0.0,Good food--loved the gnocchi with marinara\nth...,2009-10-14 19:57:14,NaN
2,631e9f7fedf65856ab0dfe42,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1.0,0.0,1.0,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03,NaN
3,631e9f7fedf65856ab0dfe43,J-4NdnDZ0pUQaUEEwDI9KQ,vrKkXsozqqecF3CW4cGaVQ,rjuWz_AD3WfXJc03AhIO_w,5.0,2.0,2.0,2.0,I thoroughly enjoyed the show. Chill way to s...,2012-12-04 16:46:20,NaN
4,631e9f7fedf65856ab0dfe55,JBWZmBy69VMggxj3eYn17Q,aFa96pz67TwOFu4Weq5Agg,kq5Ghhh14r-eCxlVmlyd8w,5.0,0.0,0.0,0.0,My boyfriend and I tried this deli for the fir...,2018-08-23 21:39:38,NaN
...,...,...,...,...,...,...,...,...,...,...,...
855075,6327b03050426527167a1746,nan,uChvFHK4uSifUXBPJPp9Zw,lCetcbxQr52TTGmGmXzQcw,NaN,NaN,NaN,NaN,Racist!!! Wont serve you if you are ethnic,2013-12-15 04:51:26,1.0
855076,6327b03050426527167a1749,nan,lP_cx94U8stOuQ8HrGecdQ,03jQGGJ2ch0uHTtW-UUUqg,NaN,NaN,NaN,NaN,Stuff face time.,2012-05-27 14:06:04,0.0
855077,6327b03050426527167a174c,nan,Rr4cLb6Go91FT134o6RsKg,UEGZ1nHUVb2ltGtd7C7X9w,NaN,NaN,NaN,NaN,Blizzard,2012-06-05 20:34:27,0.0
855078,6327b03050426527167a175b,nan,pflneuKFKQKQvZGDxebGFw,zsaDvomuMLe_-Ibtk9sA-A,NaN,NaN,NaN,NaN,Stopped by and it was closed on wed. 10/3/12!,2012-10-03 16:33:53,0.0
855079,6327b03050426527167a176e,nan,G0Mu95b3NXx3EO7gw6B1Zw,2YyIIdwnYv5cApn1gZo_gw,NaN,NaN,NaN,NaN,Using a restaurant.com coupon...go get one!,2012-02-07 17:46:42,0.0

In [10]:
philly_users

,index,_id,user_id,name,review_count,yelping_since,useful,funny,cool,elite,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,4,631ea1f7abab926ea88770d7,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...",...,264,184,157,251,1847,7054,3131,3131,1521,1946
1,6,631ea1f7abab926ea88770d9,AUi8MPWJ0mLkMfwbui27lg,John,109,2010-01-07 18:32:04,154,20,23,,...,0,0,0,0,1,6,3,3,0,0
2,12,631ea1f7abab926ea88770df,1McG5Rn_UDkmlkZOrsdptg,Teresa,7,2009-05-26 16:11:11,18,3,13,,...,0,0,0,0,1,0,2,2,0,0
3,21,631ea1f7abab926ea88770e8,q_QQ5kBBwlCcbL1s4NVK3g,Jane,1221,2005-03-14 20:26:35,14953,9940,11211,"2006,2007,2008,2009,2010,2011,2012,2013,2014",...,163,191,361,147,1212,5696,2543,2543,815,323
4,22,631ea1f7abab926ea88770e9,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,...,65,55,56,18,232,844,467,467,239,180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245406,1987805,631ea2f2abab926ea8a5c5b0,Tr2yeddopDzMhSb7jbdNeA,Heather,1,2017-07-25 19:31:30,0,0,0,,...,0,0,0,0,0,0,0,0,0,0
245407,1987831,631ea2f2abab926ea8a5c5ca,XTWARBzLbiJKQ1JeJB9f3g,Sakina,6,2017-11-24 03:17:11,1,0,0,,...,0,0,0,0,0,0,0,0,0,0
245408,1987832,631ea2f2abab926ea8a5c5cb,iZ0puydkFQlaSQAXbGtv1g,Dr. Sylvia,1,2014-07-08 19:54:19,2,0,0,,...,0,0,0,0,0,0,0,0,0,0
245409,1987859,631ea2f2abab926ea8a5c5e6,K-BNvWUCWEGUuBirCU4mmg,Jodi,2,2015-03-23 17:29:22,0,0,0,,...,0,0,0,0,0,0,0,0,0,0
245410,1987889,631ea2f2abab926ea8a5c604,fB3jbHi3m0L2KgGOxBv6uw,Jerrold,23,2015-01-06 00:31:31,7,0,0,,...,0,0,0,0,0,0,0,0,0,0